version: '3.1'
services:
  mongo:
    image: mongo:5.0.3
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ash
      MONGO_INITDB_ROOT_PASSWORD: demo
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ash
      ME_CONFIG_MONGODB_ADMINPASSWORD: demo
      ME_CONFIG_MONGODB_URL: mongodb://ash:demo@mongo:27017/
